### ISSUE TITLE
About pose estimation issue on YFCC100M dataset

### ISSUE THREAD

**Issue by vdvchen** [magicleap/SuperGluePretrainedNetwork#1]
Thank you very much for releasing the official implementation of superglue.

I'm trying to test the pose estimation performance on YFCC100M(using the same test sequences as in superglue paper) with command python match_pairs.py --resize 1600 --superglue outdoor --max_keypoints 2048 --nms_radius 3 --resize_float  --eval, but get some strange results.

The auc @5/10/20 are 39.08/59.18/75.28, which are lower than reported.  After investigation, I find some pairs with very high matching inlier ratio but low pose accuracy, see the picture below for example.
![34511353_8612252871_58780959_4178228_evaluation](https://user-images.githubusercontent.com/32128903/77061698-a565ef80-6a15-11ea-84a4-a05aabc778a5.png)

This pair have nearly 100% inlier ratio but the angular error for translation is high(27.5 degrees).  

Is there any explanation for such results? Also do you have any suggestions on reproducing the performance on YFCC100M?

**Comment by ddetone** [comment]
Hi. Thanks for reaching out. We are digging into this and will update you soon.

**Comment by ddetone** [comment]
Hello,

Thanks again for this detailed issue and for including the visualization. I believe that at the core of your issue there are actually two questions:

1.) **Why are my AUC numbers different than what is reported in the paper?** First off, assuming you are reporting the "Exact AUC" numbers from the github code, then actually are are getting *better numbers* than what is in the arxiv paper.

We dug into our internal evaluation code that we used for the paper, and found that we weren't handling the image resizing properly for the SuperPoint methods in the YFCC evaluation. We re-ran those numbers and they will be included in the new arxiv version (coming out this evening), as well as the CVPR camera ready. So thank you @vdvchen !

To make comparisons on YFCC easier, we also updated the README with directions as well as a pairs file with the ground truth in our format to make it easier to reproduce our YFCC numbers.

2.) **Why does superglue give me very strong matches, yet my final pose is off?** The short answer is that we use a simple RANSAC pose estimation routine from OpenCV that has some blind spots when estimating relative epipolar geometry. We re-ran SuperGlue on the example you provided and got a similar result. One hypothesis is that the scene is mostly planar, and the epipolar geometry is degenerate in this case. You might be interested in some more "robust" RANSAC pose estimation routines like [DEGENSAC](http://cmp.felk.cvut.cz/ftp/articles/chum/chum-cvpr05a.pdf) that handle planar vs non-planar geometries differently. You'll notice that generally it's easier to get the correct Rotation in these cases, but harder to get the correct Translation.

Hope this helps, and thanks for helping us make the paper and code better!

**Comment by punisher220** [comment]
Excuse me, @ddetone  I am trying to perform homography transformation to do image pair fusion.
I wonder the values in your match result npz file in key "keypoints0". 
Are they the X,Y values of the keypoints pixel coordinates in image 1 and the "keypoints1" refer to image2?
Just the same as the SIFT implementation in OpenCV did as **queryIdx.pt** and **trainIdx.pt**?
Is it right?

**Comment by Skydes** [comment]
@punisher220 Please open a new issues if you have questions. Please check the code if you have any doubt. `keypoints0/1` are detected in images 0 and 1. The matches are saved in `matches0`, which are indexes of `keypoints1` corresponding to each `keypoint0`, and -1 if there is no match.
https://github.com/magicleap/SuperGluePretrainedNetwork/blob/184680fb7455cdd0b35df98ad220a2a6a7640980/match_pairs.py#L286-L288

**Comment by punisher220** [comment]
@Skydes Thanks for your reply. I opened a new issue just now.
In addition I combined the keypoint data from image 0 and image 1 as you did in the reply.
