### ISSUE TITLE
Evaluation code on visual localization challenge benchmark.

### ISSUE THREAD

**Issue by kxhit** [magicleap/SuperGluePretrainedNetwork#10]
Hi! Thanks for sharing your work! Congratulations on winning the 1st place in [CVPR2020 visual localization challenge](https://www.visuallocalization.net/workshop/cvpr/2020/)!

I'm a beginner in this field and I wanna learn your technical proposal. Will you open source the competition code? (e.g. parameter settings, evaluation codes, training details) Is there any new technical report except for this paper?

Thanks a lot!

**Comment by Skydes** [comment]
Thanks :) The pipeline is mostly based on our CVPR 2019 codebase, which can be found here: https://github.com/ethz-asl/hfnet I will publish later on (few weeks) a clean PyTorch version that includes SuperGlue. In the meantime, you can use this repository - simply use the outdoor model and the hyperparameters described in our submission info.

**Comment by kxhit** [comment]
Thanks for your reply! Looking forward to the new version! I will have a try with this repository.

**Comment by kxhit** [comment]
Hi! Excuse me. The SfM model cannot be downloaded [here](https://projects.asl.ethz.ch/datasets/doku.php?id=cvpr2019hfnet). 
 I met ```Forbidden You don't have permission to access this resource.```
Could you check that? Thanks a lot!

**Comment by kxhit** [comment]
I can download them now.

**Comment by kxhit** [comment]
@Skydes Hi!
    I'm trying to integrate superglue into hfnet. I found that the scores of superpoint are not retained in 3D model in hfnet. However, scores are needed in superglue. Thus, I have to rebuild the 3D model with scores reserved by COLMAP. 
    Is there an easier solution? Cause I can't guarantee the rebuilded 3D model is the same as the 3D model you gave. Could you release a 3D model with the scores? Or could you please give me some specific instructions? 
Thanks a lot!
