### ISSUE TITLE
ORB+SuperGlue

### ISSUE THREAD

**Issue by szgy66** [magicleap/SuperGluePretrainedNetwork#106]
Hello, firstly, thank you for contributing to such a successful project. At present, I am in contact with SLAM system. Due to real-time requirements, I use ORB for feature point matching, but due to the reasons of the scene, the matching rate is low and the error rate is high. So I wanted to use ORB+SuperGlue (partly because the ORB descriptor length is 256), but I found the results to be surprisingly poor, I think the code can be fixed, so I was wondering if you tried combining ORB with SuperGlue? I don't see it in the article. Looking forward to your reply。

**Comment by Fryman420** [comment]
See this repository https://github.com/cvg/Hierarchical-Localization
They are using SFM algorithms with SuperGlue keypoints insetad of SIFT. This can partly solve your problem
