### ISSUE TITLE
How to estimate homography for RANSAC and DLT ? 

### ISSUE THREAD

**Issue by akif-caglar** [magicleap/SuperGluePretrainedNetwork#111]
Hi, first of all thank you for your amazing work.

I wanted to know how did you estimate homography with RANSAC and DLT for the results at Table 1 of your paper ? Have you used cv::findHomography() function for both ? I could not find it in your source code.

Thank you very much.

**Comment by sarlinpe** [comment]
Homography estimation with RANSAC is indeed based on `cv2.findHomography`. For DLT, we implemented a weighted version in a few lines of numpy code. For reference, here is a weighted 8-point algorithm for essential matrix estimation: https://github.com/Skydes/SuperGluePretrainedNetwork/blob/master/models/utils.py#L297-L316
