### ISSUE TITLE
How do you adjust the ratio between matched and unmatched loss?

### ISSUE THREAD

**Issue by yogurt2077** [magicleap/SuperGluePretrainedNetwork#115]
First of all, thank you for your great work! 
I am trying to train SuperGlue on MegaDepth, but it's hard to adjust the ratio between matched and unmatched loss since the number of unmatched point is far more than the matched. So I want to ask how do you balance the lambda or ratio of the matched loss and unmatched loss? Or you are doing the balance by adjusting the dataset or other methods?
Thanks a lot!

**Comment by yogurt2077** [comment]
Any tips on how to adjust the matched and unmatched lambda based on monitoring the Recall(Matching Score) and Precision on validation set of Megadepth? Any kind of help would be highly appreciated !
@Skydes

**Comment by sarlinpe** [comment]
Sorry for the late reply. [As referenced in a previous reply](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/31#issuecomment-684986482), equally balancing the positive and negative losses can help the training. You could indeed also do it based on the precision and recall of the validation set.

**Comment by yogurt2077** [comment]
> Sorry for the late reply. [As referenced in a previous reply](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/31#issuecomment-684986482), equally balancing the positive and negative losses can help the training. You could indeed also do it based on the precision and recall of the validation set.

thx for the reply!I'll try.
