### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by saroo25** [magicleap/SuperGluePretrainedNetwork#118]
Hi, i am trying to extract features from images using only superpoint, with this simple script, but when launching superpoint I get this error message:
Traceback (most recent call last):
  File "SP_ex.py", line 57, in <module>
    main()
  File "SP_ex.py", line 45, in main
    pred0 = superpoint({'image': inp0})
  File "C:\Users\rfort\anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rfort\Documents\GitHub\SuperGluePretrainedNetwork\models\superpoint.py", line 153, in forward
    x = self.relu(self.conv1a(data['image']))
  File "C:\Users\rfort\anaconda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\rfort\anaconda3\envs\py38\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\rfort\anaconda3\envs\py38\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 2.15 GiB (GPU 0; 2.00 GiB total capacity; 39.39 MiB already allocated; 1.27 GiB free; 60.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```python
from distutils.command.config import config
from models.utils import read_image
import os
import string
from tokenize import String
from models.superpoint import SuperPoint
import numpy as np
import torch
import gc

def jpg_identifier(assets:list):
    images=[]
    for path in assets:
        if ".jpg" in path:
            images.append(path)
            
    return images

def list_assets(path:String):
    return os.listdir(path)





def main() -> None:
    list=list_assets("query")
    list=jpg_identifier(list)
    config={'superpoint': {'nms_radius': 4, 'keypoint_threshold': 0.005, 'max_keypoints': 1024},
         'superglue': {'weights': 'indoor', 'sinkhorn_iterations': 20, 'match_threshold': 0.2}}
    
   
    image=list[0]
   
    
    superpoint = SuperPoint(config.get('superpoint',{})).to('cuda')
    
    image0, inp0, scales0 = read_image("query"+"/"+ image, device='cuda', resize=[-1], rotation=0, resize_float=True)
    
    
    pred = {}
    print("PERCHE SI BLOCCAAAA:: ",inp0)
    pred0 = superpoint({'image': inp0})
    pred = {**pred, **{k+'0': v for k, v in pred0.items()}}
    
    print("keypoits immagine ",image," Predicted: ",pred)

**Comment by saroo25** [comment]
@Skydes @romachalm @Babilinski

**Comment by sarlinpe** [comment]
You don't have much GPU memory here, try resizing the images to a lower resolution.

**Comment by saroo25** [comment]
Thanks resizing the images worked.
