### ISSUE TITLE
Why the model could not be loaded? 

### ISSUE THREAD

**Issue by hiakru** [magicleap/SuperGluePretrainedNetwork#12]
![image](https://user-images.githubusercontent.com/33151098/86902602-c2e3d400-c140-11ea-9566-bc1fb3cb227d.png)

Is there any special configure for python or pytouch?

**Comment by Skydes** [comment]
It seems that this usage of `pathlib` works [only for Python >= 3.6](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t). Alternatively, replace `path` with `str(path)` [here](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py#L226). Thanks for reporting this.

**Comment by hiakru** [comment]
Worked! Upgrade from 3.5 to 3.6, Thanks~
