### ISSUE TITLE
Question about the pose estimation from key points 

### ISSUE THREAD

**Issue by HJoonKwon** [magicleap/SuperGluePretrainedNetwork#141]
I have a question about the function `estimate_pose` in utils.py, especially [this part](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/utils.py#L292).

If the purpose of this line was to calculate the mean of focal lengths (for all axes), shouldn't it be like 
```f_mean = np.mean([K0[0, 0], K0[1, 1], K1[0, 0], K1[1, 1]])``` ? 
The original code seems redundant. Or is it because we assume that ```fx==fy```?

**Comment by sarlinpe** [comment]
Good catch, this is a small unintended bug. It should not have much impact on the results because for most images indeed `fx==fy`.

**Comment by HJoonKwon** [comment]
Understood, I appreciate the clarification!
