### ISSUE TITLE
A question about self-attention visualization in the paper.

### ISSUE THREAD

**Issue by RoyAmoyal** [magicleap/SuperGluePretrainedNetwork#142]
Hey, 

In the self-attention visualization, it looks like not all the key points have an "edge" with attention score in the graph attention. In practice, every key point is supposed to have some attention from all the other key points in the image, so did you remove some of them just for better visualization, or am I missing something?

Same question for the cross attention. 

for example, the blue key point doesn't have a graph attention edges with all the other key points
 ![image](https://github.com/magicleap/SuperGluePretrainedNetwork/assets/69425073/c16cbe0f-627c-487d-ba2e-57634902c2ad)

Thanks, great paper, and great visualization!

**Comment by sarlinpe** [comment]
In this visualization, the opacity of each line is set to the value of the attention weight. To keep the file size low, we only plot lines whose opacity is larger than some small value.

**Comment by RoyAmoyal** [comment]
@Skydes 
So in practice, each key point is supposed to have "lines" to all the other key points, right? 

Thanks for the fast response!

**Comment by sarlinpe** [comment]
Yes, but here we show the attention weights for a single query point.

**Comment by RoyAmoyal** [comment]
Thanks!
