### ISSUE TITLE
Sinkhorm Algorithm

### ISSUE THREAD

**Issue by batman-far** [magicleap/SuperGluePretrainedNetwork#15]
Does implemented Sinkhorm algorithm assumes there should be same number of key-points in both images? If the answer is yes, how situations that there is no same number of key-points is handled?

**Comment by Skydes** [comment]
Please read [the associated paper](https://arxiv.org/abs/1911.11763), especially Section 3.2. Our optimal matching layer does **not** assume that the two images have the same number of keypoints. We achieve this using optimal transport.
