### ISSUE TITLE
Some details about homography trained models

### ISSUE THREAD

**Issue by Cuistiano** [magicleap/SuperGluePretrainedNetwork#16]
Thanks for the excellent work! I have some questions about the homography trained models.
1). What is the threshold of correct matches when evaluating the Recall and Precision of HPatches dataset by synthetic homography trained model? 
2). Have you tested the MMA of HPatches by synthetic homography trained model?  
3). Does big homography dataset matters during training? Could I train the model with fewer data ？
I would appreciate it if you could give me a reply :)

**Comment by Skydes** [comment]
Thank you!

1. I think that we used a threshold of 3 pixels after having resized the images to VGA 640x840.
2. I don't think that the MMA would be a suitable metric here: it essentially corresponds to the precision, which can be trivially maximized by predicting very few correct correspondences. It is only fair when used with the recall, or when the number of matches is fixed across methods, which is not possible with SuperGlue.
3. We trained with about 300k different images, but I don't think that you need so much. MS COCO, on which SuperPoint was trained, has about 80k images. What matters more is the extreme extent of the homographic and photometric augmentation.

**Comment by Cuistiano** [comment]
Thanks for your detailed reply, I got it :)
