### ISSUE TITLE
parameter z and alpha

### ISSUE THREAD

**Issue by batman-far** [magicleap/SuperGluePretrainedNetwork#17]
I can not find learnable parameter z that is referred in the paper in the code. According the paper z is used to fill dustbins.

1-Where is z in the code?
2-Does z is fixed during test time for any input pair?
3-What is parameter alpha in def log_optimal_transport(scores, alpha, iters: int) ?

I would be great if you give me a reply.

**Comment by Skydes** [comment]
The parameter z is called [`bin_score`](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py#L220). In the function [`log_optimal_transport`](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/models/superglue.py#L152) it is called `alpha`. Sorry for the confusion, the notation was changed when writing the paper.

**Comment by Skydes** [comment]
Please close this issue if it is resolved. Thanks.
