### ISSUE TITLE
SuperPoint model sample descriptor

### ISSUE THREAD

**Issue by ppinheiro2** [magicleap/SuperGluePretrainedNetwork#18]
Hi, I've seen the SuperPoint repo and now that I'm comparing to this one I noticed a slightly different way of interpolating the descriptors from the keypoint locations. I don't understand this two lines

keypoints = keypoints - s / 2 + 0.5
keypoints /= torch.tensor([(w*s - s/2 - 0.5), (h*s - s/2 - 0.5)],
                              ).to(keypoints)[None]

Could you explain me the difference between this implementation and simply dividing by the dimensions of the image?

Thank you for this great work!

**Comment by Skydes** [comment]
Hi, that's a good catch!

The original SuperPoint repo scales the keypoints (i, j) by (1/W, 1/H). This is not correct if the image is downsampled by stride-2 max pooling: the pixel (0, 0) in the final descriptor map (with stride 8) is actually (3.5, 3.5) in the input image - it is in the center of the receptive field at (0, 0).

The keypoint scaling in this codebase was an attempt to do the scaling properly (I don't have the derivation anymore). It is unfortunately not correct, but we kept it anyway to be consistent with the results reported in the paper. The correct way of doing it is roughly `i -> (i - 0.5) / 2` at each level, [as done correctly by D2-Net](https://github.com/mihaidusmanu/d2-net/blob/master/lib/utils.py#L70).

**Comment by ppinheiro2** [comment]
Hi @Skydes ,

Thank you for the answer. So, the correct way of doing it is i -> (i - 0.5) / 2 at each level, which comes i->(i-3.5)/8 since the network has 3 max pooling layers.

**Comment by Skydes** [comment]
Yes, that is correct.

**Comment by ppinheiro2** [comment]
Hi @Skydes,
I've been trying to evaluate Superpoint and get the descriptors for matching and I've noticed that when I interpolate all the descriptor map (using torch.nn.functional.interpolate) and then choose the descriptors on keypoint locations, I get many matches and very good ones.
However, when I've tried this approach of interpolating only the descriptors at keypoint locations after downsampling the coordinates (using torch.nn.functional.grid_sampler), the matches are much less e almost all of them are incorrect.
I was trying this approach to improve the runtime. 
Do you have an idea of what could be causing this problem?

I really appreciate your help,
Pedro

**Comment by Skydes** [comment]
The keypoint locations given to `grid_sampler` are probably out of the [-1, +1] range - the scaling might be incorrect. Please compare with the existing code.

**Comment by ppinheiro2** [comment]
Thank you for the answer. I am still getting the same problem. 
1) Magicleap pretrained weights, with interpolation of all the descriptor map and then selecting descriptors from keypoint locations
![result_good](https://user-images.githubusercontent.com/68388976/88690645-c8a35880-d0f3-11ea-9e3a-989603e05646.png)

2) Magicleap pretrained weights, with descriptor interpolation only in keypoint locations with the function `sample_descriptors` from SuperGlue repo
![result](https://user-images.githubusercontent.com/68388976/88690383-867a1700-d0f3-11ea-93ef-3dbbc415a955.png)
In this last approach, several descriptors are a vector of zeros and almost all the matches are wrong.
In both examples, matching is done by NN

**Comment by Skydes** [comment]
This confirms that the keypoint scaling of `grid_sample` is incorrect. Please double check your code before asking for help, or post a code snippet.

**Comment by ppinheiro2** [comment]
Thank you for all the clarifications, I found my mistake, I misunderstood the `grid_sample` documentation and I wasn't converting from (h,w) to (x,y). I'm sorry about this misunderstanding. 
I still have 2 small questions:
1) The downscalling shouldn't be `i' = (i - 3.5) / (8 * (w-1)) * 2 - 1`? Because the coordinates are in the range [0,w-1]
2) About the `align_corners`, the correct way is `align_corners=True`, even with this scalling?

Thank you again @Skydes

**Comment by Skydes** [comment]
You are right, `i' = (i - 3.5) / (8 * (w-1)) * 2 - 1` is actually the correct way. `align_corners` should be True.

**Comment by Skydes** [comment]
Please close this issues if your problem is resolved. Thanks!
