### ISSUE TITLE
[Discussion] Grey-scale image as an input?

### ISSUE THREAD

**Issue by shuangliu1993** [magicleap/SuperGluePretrainedNetwork#2]
Hey there thank you so much for sharing your brilliant work!

I have one question, why we read images as grey-scaled ones in the demo? Is that what the current algorithm only supports for now? I am curious because to me it seems like color information can greatly help feature detection and matching.

**Comment by ddetone** [comment]
This is mostly an artifact of how the underlying SuperPoint model was trained. Like many feature detectors before it (e.g. SIFT), it operates on grayscale intensities. We found that by training on grayscale it helps improve generalization, though it seems reasonable that additional distinctiveness could come from learned color descriptors. I'd be interested to see improved results with colored SuperPoint + SuperGlue!
