### ISSUE TITLE
Can you provide pt file

### ISSUE THREAD

**Issue by zzl20** [magicleap/SuperGluePretrainedNetwork#21]
Hi，is it convenient to provide pt files?

**Comment by Skydes** [comment]
Hi, what do you mean by "pt files"? Are you referring to the PhotoTourism dataset? If yes, we will not provide any files - please use the new [Image Matching Benchmark 2020](https://vision.uvic.ca/image-matching-challenge/).

**Comment by zzl20** [comment]
> Hi, what do you mean by "pt files"? Are you referring to the PhotoTourism dataset? If yes, we will not provide any files - please use the new [Image Matching Benchmark 2020](https://vision.uvic.ca/image-matching-challenge/).
Sorry， In the "weight"  file include surperpoint.pth and surperglue.pth, i want use this network in c++ by libtorch, so can you provide surperpoint.pt and surperglue.pt

**Comment by Skydes** [comment]
For this you need to trace the model and save it as TorchScript. The instructions are [here](https://pytorch.org/tutorials/advanced/cpp_export.html). The SuperGlue model is traceable in PyTorch >= 1.1. For SuperPoint you might need some adjustments.

**Comment by zzl20** [comment]
> For this you need to trace the model and save it as TorchScript. The instructions are [here](https://pytorch.org/tutorials/advanced/cpp_export.html). The SuperGlue model is traceable in PyTorch >= 1.1. For SuperPoint you might need some adjustments.

Thank you very much !

**Comment by Skydes** [comment]
Please consider closing this issue if your problem is solved. Thanks :)

**Comment by valgur** [comment]
Here's a small C++ demo project for SuperGlue that also includes some minor tweaks to the model definitions needed for TorchScript compatibility, which you might find useful: https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo.

As a small bonus, the jitted model runs about 20% faster than the un-jitted one in both Python and C++.

**Comment by Skydes** [comment]
Wow this is great, thank you for sharing it. AFAIK inheriting from `torch.jit.ScriptModule` is not necessary for PyTorch >= 1.2: https://pytorch.org/docs/master/jit.html#migrating-to-pytorch-1-2-recursive-scripting-api It would be nice to see what are the minimum changes required to the model definition for scripting to work - maybe we can integrate it into the repo if it's minimal enough.

**Comment by ddetone** [comment]
Hello @valgur, thank you helping with the TorchScript compatibility. Please close this issue if you have no further problems :)

**Comment by Skydes** [comment]
Hi @waicool20, I do not intend to merge them as we want to keep this repos as simple as possible.

Hi @zzl20, could you please close this issue if your problem is solved? Thank you.
