### ISSUE TITLE
Would you mind sharing the model trained on synthetic homographies? 

### ISSUE THREAD

**Issue by Cuistiano** [magicleap/SuperGluePretrainedNetwork#22]
Hello, I want to reproduce the Table5(Generalization to real data) in the paper, but the Precision and Recall tested by the model you shared (outdoor) are a little bit different from that(Recall increased while precision decreased). Would you mind sharing the model trained on synthetic homographies?

**Comment by Skydes** [comment]
Hi, we do not plan to release the weights of the SuperGlue model trained on synthetic homographies. Since HPatches evaluation is merely a sanity check before applying to real world problems, I think that the using the outdoor model makes more sense here.

**Comment by Cuistiano** [comment]
I see. Thank you!
