### ISSUE TITLE
mismatch problem in c++

### ISSUE THREAD

**Issue by zzl20** [magicleap/SuperGluePretrainedNetwork#23]
hi, i used the superglue modle in c++ by libtorch, but the matching result of superglue apper some mismatches.  
![smatch](https://user-images.githubusercontent.com/26411422/89150781-ebb98680-d591-11ea-9e29-68cac6ad64c7.png)

i change the file "superglue.pth" into "superglue.pt",  according to the "'matches0': indices0"  match point
![pt](https://user-images.githubusercontent.com/26411422/89151046-9762d680-d592-11ea-888e-003262e71f86.png)

how to deal with the mismatch ?  In python code , just according to the "matches0" .

**Comment by Skydes** [comment]
I don't understand your question. I can't provide support for the C++ because I haven't tried it myself. The lines that you show look valid, so your issue is due to something else. Only `indices0` are necessary for obtaining the matches, so I don't get why you also need `indices1`. In the picture that you show all matches are incorrect - check that the network is initialized and not random.

**Comment by zzl20** [comment]
> I don't understand your question. I can't provide support for the C++ because I haven't tried it myself. The lines that you show look valid, so your issue is due to something else. Only `indices0` are necessary for obtaining the matches, so I don't get why you also need `indices1`. In the picture that you show all matches are incorrect - check that the network is initialized and not random.

![pt1](https://user-images.githubusercontent.com/26411422/89158320-7d2ff500-d5a0-11ea-82c0-d3fec4b0da23.png)
As picture show, i got some random data as the  input of the superglue network.

I check my own code, but the result of matching still have  wrong matches.
![newmatch](https://user-images.githubusercontent.com/26411422/89164180-54f8c400-d5a9-11ea-85aa-c0bd638f621a.png)

**Comment by Sijin0309** [comment]
@zzl20 Hi, when I trace superglue, I get the following error:
```
RuntimeError: 
Can not iterate over a module list or tuple with a value that does not have a statically determinable length
:
  File "models/superglue.py", line 131
    def forward(self, desc0, desc1):
        for layer, name in zip(self.layers, self.names):
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            if name == 'cross':
                src0, src1 = desc1, desc0
```
Do you trace only part of model? Or doing some tricks to make it work? Looking forward to your reply, thanks!

**Comment by Skydes** [comment]
@valgur successfully JIT-ed the model, and had to change a few lines: https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo#diff-d1570bbe943a4cbb15142d7bb296e124L132 Maybe these changes are also required for tracing to work.

**Comment by Sijin0309** [comment]
> @valgur successfully JIT-ed the model, and had to change a few lines: [master...valgur:cpp-demodiff-d1570bbe943a4cbb15142d7bb296e124L132](https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demodiff-d1570bbe943a4cbb15142d7bb296e124L132) Maybe these changes are also required for tracing to work.

Thank you! I will take a shot.

**Comment by ddetone** [comment]
Hello @Sijin0309, please close this issue if you have no further problems :)

**Comment by Sijin0309** [comment]
> Hello @Sijin0309, please close this issue if you have no further problems :)

This issue is opened by @zzl20 . Maybe it is better to ask him.

**Comment by ddetone** [comment]
Sorry about that @Sijin0309, I meant @zzl20 ! Normally I would close it myself since the issue seems resolved, but I currently don't have the right permissions for that. Thanks!
