### ISSUE TITLE
Question about phototourism test pairs

### ISSUE THREAD

**Issue by vdvchen** [magicleap/SuperGluePretrainedNetwork#27]
Hi,

Thank you for releasing test pairs for outdoor evaluation on phototourism dataset.  However, I'm a little confused about the data format of  _asset/phototourism_test_pairs.txt_ . I assume that the first 2 strings in each row correspond to the names of the two images used in each pair but I find that they are the same in every row. In addition, I'm wondering what the last two numbers in each row stand for?

![sad](https://user-images.githubusercontent.com/32128903/90363044-83d86500-e094-11ea-92fa-dfea3f75be3f.png)

Thank you for your attention.

**Comment by Skydes** [comment]
Thank you for bringing this up. The two names should be different in each row, so there was probably a bug in the generation process. @ddetone can maybe confirm. In the meantime you can use names from the [previous version of the file](https://github.com/magicleap/SuperGluePretrainedNetwork/blob/45a750e5707696da49472f1cad35b0b203325417/assets/phototourism_test_pairs.txt). The last two numbers in the new file correspond to the EXIF rotation of the first and second image, as explained [in the README](https://github.com/magicleap/SuperGluePretrainedNetwork#test-set-pair-file-format-explained).

**Comment by vdvchen** [comment]
Thank you very much for the calrification.  Will try to use this file.

**Comment by vdvchen** [comment]
Sorry for bothering again.  I encountered some problems while trying to reproduce the numbers for photourism dataset. 

In order to calibrate the further experiments, I run the sift baseline with NN and ratio test. However, the exact auc@5,10,20 I obtained is 7.9/14.9/24.8, which is lower than the number reported(15.19/24.72/35.30).  

Here are the detailed experiment settings.
I resize all the images so that their longest dimension is 1600, extract 2048 sift keypoints with opencv sift extractor, perform nn match ,run ratio test(tuning from 0.8-0.95)  to remove outliers. For pose estimation, I use opencv findessentialMat and recoverpose where the RANSAC threshold is set by 1 pixel in the resized image. I use the ground truth in YFCC dataset to evaluate the pose auc. 

Did I miss something in the procedure? Thank you very much for your attention.

**Comment by ddetone** [comment]
@vdvchen @Skydes thanks for catching that! I'll work on a fix

@vdvchen Were you able to first reproduce the SIFT numbers on YFCC?

**Comment by Skydes** [comment]
@vdvchen are you evaluating on YFCC or Phototourism? The ground truth of the latter is not public.

If you are referring to YFCC, then you should look at Table 6 instead. There `SIFT + NN + ratio test` gives `24.09/40.71/58.14` exact AUC. These numbers are notably higher than the ones you report. Some pointers:
1. We use **root-normalized** SIFT (RootSIFT) as described in Section 5.2
2. Have you tried also tunning the RANSAC error threshold?

**Comment by vdvchen** [comment]
> @vdvchen @Skydes thanks for catching that! I'll work on a fix
> 
> @vdvchen Were you able to first reproduce the SIFT numbers on YFCC?

Yes, I can reproduce the numbers on YFCC dataset(Table 6) with both sift and superpoint(and their combinations with superglue) but failed when reproducing the numbers on Table3.

**Comment by vdvchen** [comment]
> @vdvchen are you evaluating on YFCC or Phototourism? The ground truth of the latter is not public.
> 
> If you are referring to YFCC, then you should look at Table 6 instead. There `SIFT + NN + ratio test` gives `24.09/40.71/58.14` exact AUC. These numbers are notably higher than the ones you report. Some pointers:
> 
>     1. We use **root-normalized** SIFT (RootSIFT) as described in Section 5.2
> 
>     2. Have you tried also tunning the RANSAC error threshold?

Thank you for the clarification. I can reproduce the result in Table 6(actually the number for sift with superglue trained on our dataset is even a little higher than that reported in the paper). I'm referring to Table3, which I think should correspond to the 2200 pairs in _asset/phototourism_test_pairs.txt_.  Since I find these pairs are also included in the YFCC dataset, I use the pose ground truth in YFCC to do AUC evaluation. I guess the gap might caused by the difference between the GTs( the ground truth from Image Matching Challenge might be more accurate).

And another thing, is rootsift instead of sift used in Table 2,3,6?

Thank you for your attention.

**Comment by Skydes** [comment]
Ah I didn't know that all the images are also in YFCC. The ground truth is certainly different, and I too would assume that PhotoTourism is much accurate.

> And another thing, is rootsift instead of sift used in Table 2,3,6?

Yes, we used RootSIFT in all evaluations.

**Comment by Skydes** [comment]
Hi @vdvchen, did you try the new test pair file fixed by #30? If that works for you, please close this issue. Thanks!

**Comment by DylanWusee** [comment]
> Ah I didn't know that all the images are also in YFCC. The ground truth is certainly different, and I too would assume that PhotoTourism is much accurate.
> 
> > And another thing, is rootsift instead of sift used in Table 2,3,6?
> 
> Yes, we used RootSIFT in all evaluations.

Hi, This is a very great work. I am trying to reproduce the SIFT + NN + ratio test results as in the Table. 6 in the paper. But, I could only achieve the following results:

AUC@5    AUC@10  AUC@20 
24.94         39.03        52.86 

For AUC@5, the results seems comparable. But, the AUC@10 and AUC@20 is worse than the number reported in the paper. 

I am resizing the input image to be 1600. and using number of keypoints to be 2048 and the rootSIFT. The RANSAC thresh is set to be 1. pixel in the resized images by dividing the mean of the f as the line https://github.com/magicleap/SuperGluePretrainedNetwork/blob/c0626d58c843ee0464b0fa1dd4de4059bfae0ab4/models/utils.py#L293 

Could you help me with that? 

Thank you very much.
