### ISSUE TITLE
Question about superPoint keypoint count for Indoor/Outdoor image sets

### ISSUE THREAD

**Issue by dedoogong** [magicleap/SuperGluePretrainedNetwork#3]
Thank you for your sharing of this art work. 

I know you have no plan to provide training part of superGLUE, but I have one question.

According to your paper, you said, you used 400/512 keypoints(detected by superPoint) for in/outdoor image sets. 

But, as you know, there surely could be less or more detected keypoints than that. 

What if only 50 keypoints are detected in query image? Did you add zero pad of 350 to fit the tensor shape into batch size x 400 x 256(D) ? If so, did you ignore the zero padded graph nodes  when calculating loss? 

I hope to get any hint. 

Thank you!

**Comment by Skydes** [comment]
Hi,

Thanks for your interest in SuperGlue. When fewer keypoints are detected, we sample additional ones from a uniform random distribution. We assign them a detection confidence of zero, and resample local descriptors from the semi-dense descriptor map at these locations. These are included in the matching and in the loss, and make SuperGlue robust to spurious detections. This is briefly mentioned in Section 4 of the paper.
