### ISSUE TITLE
output of log_optimal_transport

### ISSUE THREAD

**Issue by batman-far** [magicleap/SuperGluePretrainedNetwork#32]
Hello,

Output of `log_optimal_transport` function is confusing for me. I want to train a model but output of `log_optimal_transport` is ambiguous for me.

I get some negative number as output of `log_optimal_transport`. It's differential version of Hungerian algorithm. So it shouldn't be some positive number?

output of `log_optimal_transport` when it is higher shows an assignment or when it is lower?

I want to use loss function but I don't know about output of `log_optimal_transport`

**Comment by Skydes** [comment]
`log_optimal_transport` = optimal transport in log space. Exponentiate to obtain the assignment.
