### ISSUE TITLE
Is this will be supported in mobile platform? 

### ISSUE THREAD

**Issue by RamboRick** [magicleap/SuperGluePretrainedNetwork#35]
Thank you for your great work. 

I am wondering if this will be used on the smartphone platform? Or do you have any suggestions for using functions, such as mach_pairs,  with a mobile phone camera? 

Thank you again.

**Comment by Skydes** [comment]
There is a C++ demo that works with torchlib: https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo I will not provide any support beyond the code released in this repository.

**Comment by RamboRick** [comment]
Thank you.
