### ISSUE TITLE
about the paper P ̄

### ISSUE THREAD

**Issue by Usernamezhx** [magicleap/SuperGluePretrainedNetwork#36]
thanks for your work. it's so cool. about the paper. I think it should be P ̄1N+1 <= a not P ̄1N+1 = a. would you please explain why it is equal. I can understand P1N ≤1M and P⊤1M ≤1N. because you said that Set A has one correspond point to Set B at most. BTW. 
<img width="158" alt="screen" src="https://user-images.githubusercontent.com/14010625/94096681-40250800-fe57-11ea-9fd8-1da8daa73dd1.png">
partial assignment matrix is a float matrix not a [0, 1] matrix. is it right?

**Comment by Skydes** [comment]
1. We start with the partial assignment matrix P: P·1_N <= 1_M and Pᵀ·1_M <= 1_N. Then P is augmented to a full assignment matrix \bar{P} using the dustbins: \bar{P}·1_N = a and \bar{P}ᵀ·1_M = b. These are like slack variables that enforce the equality constraint.

2. SuperGlue predicts a **soft** partial assignment matrix, which indeed has float entries in [0, 1].

**Comment by Usernamezhx** [comment]
thanks for your reply.

**Comment by aa1234241** [comment]
Hi, about  \bar{P}·1_N = a, it means that the sum of dust_bin equals the total number of the key points. But if there exists any match, then that key point should not be assigned to dust_bin, and the total number, therefore, is less than N. Am I correct?

**Comment by dangnh0611** [comment]
@aa1234241 @Skydes  I have same thought. Is there any update?
