### ISSUE TITLE
Problem of getting a match in the signage picture

### ISSUE THREAD

**Issue by imamim** [magicleap/SuperGluePretrainedNetwork#37]
Thank you for your work sir. I wish you success in your work.
 
I select a signage photo I downloaded from the internet as image0 with the load_image function in ./demo_superglue.py. When I show the same picture on my phone to computer camera, I have trouble detecting the keypoint. Pairing occurs when I show it too close to the camera. When I show it from a distance that the picture is very clear and obvious, i can't get any matching!

One problem I have noticed is that the picture is slightly brighter than what is visible from the camera. 

I wonder if I should take the picture from real life ?

How should I adjust the picture dimensions and how should I set the other parameters.

Thank you in advance for the answer.

**Comment by Skydes** [comment]
Hi, I don't think that I correctly understand your problem - why would you capture with your webcam a photo display on your phone? I don't expect this to work - the display can create artifacts and low-level noise that can change the detections. I suggest to try with real pictures captured with your webcam instead.

**Comment by imamim** [comment]
Frankly, I want to use your project for object detection like SIFT does. 

When I try to detect a traffic sign, I encounter a problem like I mentioned above. When I give the train image in high resolution, I can get a match when the object is close in the camera. 

On the contrary, when I give the sign in low resolution, I can detect the traffic sign when it is far from the camera. However, this should not be the case in theory: D

 I will try the solution you just mentioned as soon as possible and report the result.

**Comment by Skydes** [comment]
As said, going through a phone display seems contrived and can give unexpected results.

**Comment by imamim** [comment]
Thanks. I tried it with real life images. The result was not exactly what I wanted. I got the similar error again. 
I guess I won't bother with this anymore. I hope you will publish this work as **SIFT-BASED**. 

I'm closing the topic for now. I congratulate you for this work. 
**Good luck !**
