### ISSUE TITLE
Have you compared your method with graph-match method?

### ISSUE THREAD

**Issue by Ru1zhi** [magicleap/SuperGluePretrainedNetwork#38]
Hi @Skydes Thank you for your sharing
Some of the existing graph matching methods[1, 2] do much the same thing as your method.
Does your method compare to them?
Or is it my own misunderstanding that your method is not comparable to them?

[1] https://github.com/Thinklab-SJTU/PCA-GM
[2] https://github.com/rusty1s/deep-graph-matching-consensus

**Comment by Skydes** [comment]
These concurrent works perform matching of semantic keypoints. As such, they are trained for a limited number of classes, and work with a very small number of keypoints, around 10 to 20. They also assume that two images in a pair have the same number of keypoints and that all of them are matchable.

On the other hand, SuperGlue matches geometric keypoints, can scale to image pairs with more than 5000 keypoints, is not limited to specific classes or scenes, and can handle unmatchable keypoints. We could also train and evaluate SuperGlue for semantic matching, but we are not interested in this application here.

**Comment by Ru1zhi** [comment]
I got it, thank you sooooooo much. 😊
