### ISSUE TITLE
About the GT depth images of Megadepth 

### ISSUE THREAD

**Issue by Cuistiano** [magicleap/SuperGluePretrainedNetwork#39]
Hello, I‘m reproducing the paper's results in Megadepth dataset recently. But  I found the depth images of Megadepth reconstructed by COLMAP(same with D2-Net) are noisy and had many outliers. Have you refined the depth images generated by COLMAP?

**Comment by Skydes** [comment]
No we don't apply any refinement, and use the depth maps provided by the MegaDepth paper as is. Having cleaner depth maps would certainly give a cleaner and denser supervision and thus better results.

**Comment by Cuistiano** [comment]
> No we don't apply any refinement, and use the depth maps provided by the MegaDepth paper as is. Having cleaner depth maps would certainly give a cleaner and denser supervision and thus better results.

Thanks for your response and clarification!
