### ISSUE TITLE
About Sinkhorn algorithm use

### ISSUE THREAD

**Issue by tiberium24** [magicleap/SuperGluePretrainedNetwork#4]
Hello,

I would like to ask you since I do not completely understand how the Sinkhorn algorithm is used on a non-square matrix N by M. I thought it could be applied only in square matrices.

Thanks in advance

**Comment by Skydes** [comment]
The Sinkhorn algorithm can indeed be used to make positive square matrices doubly stochastic, i.e. with row and columns each summing to one.

The Sinkhorn algorithm can also be used to solve entropy-regularized optimal transport problems with coupling matrices of arbitrary dimensions - provided that the posterior distributions are normalized. That's what we used, and is explained in Section 3.2 of our paper. More details can be found in Chapter 4 of the [book of Peyré & Cuturi](https://arxiv.org/abs/1803.00567).

**Comment by tiberium24** [comment]
I see your point. I am not exactly sure which part you mean by posterior distributions though. Do you mean the elements of the score matrix?

**Comment by Skydes** [comment]
Sorry, I meant **marginal** distributions - denoted as $a$ and $b$ in our paper, and referred to in Equation 9.

**Comment by tiberium24** [comment]
> The Sinkhorn algorithm can indeed be used to make positive square matrices doubly stochastic, i.e. with row and columns each summing to one.
> 
> The Sinkhorn algorithm can also be used to solve entropy-regularized optimal transport problems with coupling matrices of arbitrary dimensions - provided that the marginal distributions are normalized. That's what we used, and is explained in Section 3.2 of our paper. More details can be found in Chapter 4 of the [book of Peyré & Cuturi](https://arxiv.org/abs/1803.00567).

Can you please point me to which exact part of the book you refer to?

**Comment by Skydes** [comment]
Chapter 4, Section 2, starting on page 62.
