### ISSUE TITLE
About the pose of ScanNet

### ISSUE THREAD

**Issue by Cuistiano** [magicleap/SuperGluePretrainedNetwork#41]
Hello Sarlin, thanks for the solid work! I have reproduced the result in Megadepth :) But I encountered a problem when preprocessing ScanNet Dataset.
I reprojected one image to the other by POSE(Tcw), INTRINSIC and DEPTH, but failed(can not align them). When using SUN3D dataset(preprocessed by OANet) and Megadepth(preprocessed by D2Net), the code works. Did I miss something? Does ScanNet have a different definition of world coordinate? 
I would appreciate it if you could give me a reply :)

**Comment by Skydes** [comment]
Hi there. Great! Some sequences in ScanNet have incorrect poses, but most should be ok. I suggest to check your data preprocessing again. You might have to scale the intrinsics to fit the size of the images. I can't help much without more information.

**Comment by ZhouAo-ZA** [comment]
@Cuistiano Hello, I also recently reproduced the training process of superpoint+superglue on megadepth, but encountered some problems, may I ask if it is convenient for you to give me an email address or qq, I would like to consult with you, thank you very much

**Comment by Cuistiano** [comment]
Thank you Sarlin! Sorry for the late reply. I found the cause of  poor reprojection  lies in wrong poses of some sequences after checking more scenes:)

**Comment by santelelle** [comment]
Hi, can I ask you how did you find the sequences with wrong poses? Do you have a list of the scenes with incorrect poses?
Computing the overlap matrix between each possible pair for each scene gives me reasonable results for all the scenes. This enable me to pick up only pairs that have some overlap, but is this really filtering out all the wrong poses?

**Comment by Skydes** [comment]
I found out that some poses are incorrect by inspecting the reprojections of points for random set of image pairs with sufficient overlaps. I do not recall the scene numbers as I did anyway not exclude these scenes from the training or the evaluation. I however recall that these include bathroom scenes with repetitive, tiled floors which are challenging for feature matching or tracking.
