### ISSUE TITLE
When run "./demo_superglue.py", raise a problem about GTK+2.x and GTK+3.x

### ISSUE THREAD

**Issue by kun-dragon** [magicleap/SuperGluePretrainedNetwork#42]
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by kun-dragon** [comment]
I find the solution. There are both gtk+2.0 and gtk+3.0 in my computer, and 'cmake' opencv with gtk+2.0
so run：
 pkg-config --libs gtk+-3.0 
Then reinstall opnecv and ensure that 'cmake' with gtk3.0
cmake ..
make -j8
sudo make instal

**Comment by Skydes** [comment]
Great, thanks for sharing. @kun-dragon could you please close this issue? Thanks.
