### ISSUE TITLE
About SIFT implementation

### ISSUE THREAD

**Issue by Wenzhengchina** [magicleap/SuperGluePretrainedNetwork#43]
Hello,

Thanks for your excellent work, I'm trying to implement SIFT with your SuperGlue model. However, the length of the descriptions of  SIFT is 128. I think your model default length of the description is 256 the same as Superpoint. Because I  got such mistakes when I input the SIFT description into the SuperGlue model even I modify the parameter of 'descriptor_dim' to 128.

What should I do in this case?

**Comment by Wenzhengchina** [comment]
I'm sorry I noticed the information in Additional Notes that you do not intend to release the SIFT-based or homography SuperGlue models. And I will close this issue

**Comment by szgy66** [comment]
> I'm sorry I noticed the information in Additional Notes that you do not intend to release the SIFT-based or homography SuperGlue models. And I will close this issue

Do you had implement SIFT with SuperGlue? I also want to train my datasets with SIFT and SuperGlue.thanks!
