### ISSUE TITLE
SIFT and SuperGLue

### ISSUE THREAD

**Issue by btknzn** [magicleap/SuperGluePretrainedNetwork#45]
How can I use superglue with SIFT?

**Comment by Skydes** [comment]
No, it requires retraining for a different descriptor than SuperPoint and we don't release such model.

**Comment by btknzn** [comment]
Okey, Thank you for information. Nice work :+1:

**Comment by Skydes** [comment]
Hi @btknzn , could you please close this issue if you problem is solved? I do not have the permission to do so. Thank you.

**Comment by btknzn** [comment]
Thanks, I am closing.
