### ISSUE TITLE
Which dataset used for the released outdoor models?

### ISSUE THREAD

**Issue by noone-code** [magicleap/SuperGluePretrainedNetwork#46]
Thanks for your great work.

The presented results in YFCC are so good:
> Evaluation Results (mean over 4000 pairs):
AUC@5    AUC@10  AUC@20  Prec    MScore
39.02    59.51   75.72   98.72   23.61

While I'm confused which dataset is used for your released outdoor model which presents such great result.
Thank you so much.

**Comment by Skydes** [comment]
Please refer to the paper. The outdoor model is trained on MegaDepth.

**Comment by noone-code** [comment]
> Please refer to the paper. The outdoor model is trained on MegaDepth.

Thanks, is it trained on the scenes in the `megadepth_train_scenes.txt` ?

**Comment by noone-code** [comment]
Hi, @Skydes , Sorry to disturb you.

Recently, I am reproducing your paper. I want to confirm some details about the training data.
Does the released model `superglue_outdoor.pth` is trained under scenes be listed in the `megadepth_train_scenes.txt` ?

**Comment by Skydes** [comment]
Yes, as far as I remember, this should be correct.
