### ISSUE TITLE
A question on the attention mechanism.

### ISSUE THREAD

**Issue by csyhy1986** [magicleap/SuperGluePretrainedNetwork#48]
Your work is totally impressed me whatever in results and idea.  While I still have some questions about the attention mechanism.  In my understanding, self-attention is originally  used in sequence to sequence. For example, the input sequence is A = {a1, a2, a3, a4}, the output sequence is B = {b1, b2, b3, b4}. Then by using self-attention, a1 can be expressed into three vector q1, k1, v1, and this is similar for a2, a3, a4.  By using q1, k1 and soft-max, we can generate  α11, and repeat this we can generate α12, α13, and α14. And finally we can use α as weights to sum up v1, v2, v3, and v4 to generate b1.  So you got Equation (4).  But I can not understand Equation (5), combining with the equation αij = softmax_j(qi.t()*kj). Because I think qi and kj are generated by the first sequence, but Equation (5) qi and kj are generated from key points from different images, i.e., different sequences. This really confused me, can you explain why?

**Comment by Skydes** [comment]
Here we are working with sets, not sequences. The key and value vectors (k_j and v_j) are computed from the same set (the source set S), i.e. points in the same image. The query vectors q_i can be computed from the same or a different set (the query set Q) as k_j and v_j. This corresponds to self- and cross-attention. Equations (4) and (5) cover both cases with Q=S=A (or B) or Q=A and S=B (and conversely).

**Comment by csyhy1986** [comment]
Thanks for explanation, I think I begin to understand attention mechanism.
