### ISSUE TITLE
Integration of orb extractor with superglue

### ISSUE THREAD

**Issue by roboticsai** [magicleap/SuperGluePretrainedNetwork#49]
Is it possible to use superglue feature matching with orb feature extractor? More detail of this can be found [here](https://spectrum.chat/openvslam/beginner/integration-of-supr-glue-feature-matching-in-openvslam~b9d52a80-8f83-47e5-a8dc-ff7415cf1595).

**Comment by Skydes** [comment]
The pre-trained SuperGlue models are only compatible with SuperPoint descriptors (256d float). Matching ORB features with SuperGlue requires retraining, but we do not release the training code.

**Comment by Skydes** [comment]
Please close this issue if your problem is solved. Thank you!
