### ISSUE TITLE
Using with another descriptors' extractor

### ISSUE THREAD

**Issue by hessusH** [magicleap/SuperGluePretrainedNetwork#5]
By what should be replaced scores if I plan to use SIFT descriptors?

**Comment by Skydes** [comment]
The OpenCV KeyPoint class has an attribute for the keypoint [response](https://docs.opencv.org/3.4/d2/d29/classcv_1_1KeyPoint.html#a1f163ac418c281042e28895b20514360), which is similar to the keypoint score/confidence predicted by SuperPoint. When trained SuperGlue can decide whether this information is useful of not.

**Comment by hessusH** [comment]
Thanks a lot.
