### ISSUE TITLE
run in jetson nano

### ISSUE THREAD

**Issue by roboticsai** [magicleap/SuperGluePretrainedNetwork#50]
Is it possible to run this package on the jetson nano? I saw that jetson nano only supports pytorch instead of torch which is used by the demo script of this package.

**Comment by Skydes** [comment]
As said in the README, this repo uses PyTorch, not torch. In Python, PyTorch is imported as `torch`. As far as I know, the NVIDIA Jetson Nano can run PyTorch by using Jetson-specific pre-built binaries.

**Comment by Skydes** [comment]
Please close this issue if your problem is solved. Thank you!
