### ISSUE TITLE
How is the camera Intrinsic matrix in the yfcc_test_pairs_with_gt.txtfile obtained?

### ISSUE THREAD

**Issue by 115724Chris** [magicleap/SuperGluePretrainedNetwork#55]
Hi, I found that the K（camera Intrinsic matrix） read from the calibration directory is different from the K read from the yfcc_test_pairs_with_gt.txt. How is the K in the yfcc_test_pairs_with_gt.txtfile obtained?

**Comment by Skydes** [comment]
The intrinsics in `yfcc_test_pairs_with_gt_original.txt` and `yfcc_test_pairs_with_gt.txt` are stored as flattened `3x3` matrices `[fx, 0, cx, 0, fy, cy, 0, 0, 1]` with both focal lengths and principal points.

If the data that you are referring to is from [OA-Net](https://github.com/zjhthu/OANet), then be aware that the principal points are originally stored as offsets to the image center:
https://github.com/zjhthu/OANet/blob/master/dump_match/sequence.py#L70-L80

**Comment by 115724Chris** [comment]
> The intrinsics in `yfcc_test_pairs_with_gt_original.txt` and `yfcc_test_pairs_with_gt.txt` are stored as flattened `3x3` matrices `[fx, 0, cx, 0, fy, cy, 0, 0, 1]` with both focal lengths and principal points.
> 
> If the data that you are referring to is from [OA-Net](https://github.com/zjhthu/OANet), then be aware that the principal points are originally stored as offsets to the center pixel:
> https://github.com/zjhthu/OANet/blob/master/dump_match/sequence.py#L70-L80

Thank  you very much.
