### ISSUE TITLE
Runtime evaluation reported in the paper

### ISSUE THREAD

**Issue by GabbySuwichaya** [magicleap/SuperGluePretrainedNetwork#58]
Thank you for the great work! and for releasing the code... 

Here, I have a question for the runtime (Figure 11. Section C.) provided in the paper...   You have reported the runtime for each "Number of keypoints per image"... 

-  Is the runtime measured for a single query image? 

-  If true, does it mean that if you are matching a pair of images, would the actual runtime be twice the reported runtime? (eg. reported runtime is superglue runtime divided by 2)

**Comment by Skydes** [comment]
This runtime is computed for a pair of images, each with a similar number of keypoints.

**Comment by GabbySuwichaya** [comment]
I see. It is just that because I am interested in using SuperGlues for my application. 
However, I have a restriction in terms of runtime. 

Could you advise how did you measured it? 

I have measured the runtime with the Nsight profiler, but the runtime that I got is much higher...  
Here, I  used the Phototoursim dataset with 1600 image size, and the maximum number of keypoints is set to 1024. 

The rests of the setting are the same as the default setting.... (Sinkhorn alg. 20 iteration with 0.2 matching ratio) ... I have got the following results.


![Screenshot from 2021-02-05 18-23-07](https://user-images.githubusercontent.com/49115268/107014672-451f9e00-67df-11eb-920f-4320d63fd57c.png)

**Comment by Skydes** [comment]
This does not seem correct; 20 iterations of the Sinkhorn algorithm should not take this long. `CUDA_LAUNCH_BLOCKING` is also expected to increase the runtime as it forces synchronization at each operation. Could you please instead measure the timings with `torch.cuda.Event` as described [here](https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution)?

To speed up the inference, you could run it with JIT by first tracing it. [This branch](https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo) should make the tracing easier.

**Comment by GabbySuwichaya** [comment]
Hi @Skydes! Thanks for the confirmation, and for the suggestion of the new branch.  
I will surely try it... 
  
I found that the slow runtime was caused by the fact that I have accidentally added the double() conversion in superglue.py.  So, yes, it leads to the big synchronization. I am sorry for causing this trouble.  

Also, thanks again.
