### ISSUE TITLE
Slack variables issue

### ISSUE THREAD

**Issue by tiberium24** [magicleap/SuperGluePretrainedNetwork#6]
Hello,

I am trying to apply the Sinkhorn algorithm in a similar problem but I have an issue when introducing this slack variable. I am doing some dummy testing with two points and then adding this extra slack variable (dustbin) and it seems to not be able to reduce the loss and learn to do the assignment properly. Any thoughts?

**Comment by hagianga21** [comment]
I have the same issue. I cannot run this with any simple example.

**Comment by Skydes** [comment]
You need to penalize the assignment of unmatchable points, or the network will have no incentive to use the dustbin. In SuperGlue we do so by minimizing the negative log-likelihood of the dustbin probability of unmatchable points, as described in the second and third terms of Equation 10 of our paper. What might also help is to weight the loss of positive vs unmatched points such that they are balanced.
