### ISSUE TITLE
SuperPoint interpolation during training

### ISSUE THREAD

**Issue by zenmedou** [magicleap/SuperGluePretrainedNetwork#60]
Hi,

Thank you for this solid work.

I noticed that there might be some alternatives for superpoint interpolation in  #18. I'm wondring which method should be used to generate descriptors for training dataset.

**Comment by Skydes** [comment]
The interpolation method makes little difference. Overall SuperPoint is slightly better with the previous (incorrect) interpolation approach since it was trained with it. This however does not make much difference when using SuperGlue.

**Comment by Skydes** [comment]
Please close this issue if your problem is solved. Thank you!
