### ISSUE TITLE
How to get the homography matrix of the Megadepth dataset?

### ISSUE THREAD

**Issue by uekoh** [magicleap/SuperGluePretrainedNetwork#61]
Hi,

Thank you for this solid work.

I am working on reproducing the SuperGlue model, using the Megadepth dataset.
I am not sure how to get the homography matrix for pair images selected from the Megadepth dataset.
I think that the homography matrix can be estimated using images.txt from the Megadepth dataset and cv2.findHomography() from opencv. 
Is the above thinking correct?
If it is wrong, I would appreciate it if you could let me know.

**Comment by Skydes** [comment]
Image pairs on MegaDepth are presented by relative 6-DoF poses and depth maps, not by homographies (which correspond to planar scenes). Please refer to the paper for a description of the homography dataset.

**Comment by uekoh** [comment]
Thank you for your quick reply.
I understand now.
I will ask again if I have any questions.
