### ISSUE TITLE
How did you adjust the depth scale?

### ISSUE THREAD

**Issue by uekoh** [magicleap/SuperGluePretrainedNetwork#63]
Hi!
I'm trying to recreate a SuperGlue implementation using a megadepth dataset.
I am trying to reproject feature points using the following formula, but I am not sure of the depth scaling parameters(s0,s1). Can you give me some advice on this?

0 means camera0
1 means camera1
K means intrinsic parameter of camera
R,t means extrinsic parameter of camera
u,v means Image Coordinates point
z means depth
![image](https://user-images.githubusercontent.com/46212278/109137195-47509900-779c-11eb-8981-f0d045b62490.png)

**Comment by Skydes** [comment]
Hi there,
I don't understand where this depth scaling comes from. I don't really have time to look at this anyway, so I won't be able to help.

**Comment by uekoh** [comment]
Thank you for your answer despite the lack of time.
Could you please tell me one thing?
Are the 'depthmaps' in this [comment](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/61#issuecomment-779701699) directly using the depth values in the .h5 file in Megadepth?

If this is a misguided question, I will give up and close this issue.

**Comment by Skydes** [comment]
Yes, depthmaps are provided as HDF5 files.

**Comment by uekoh** [comment]
thank you!
I understand.
