### ISSUE TITLE
Is it possible to run with batch size > 1 

### ISSUE THREAD

**Issue by oldshuren** [magicleap/SuperGluePretrainedNetwork#64]
Hi,

Is it possible to run with batch size > 1. That is to match multiple pairs in one inference call? Because the input to SuperGlue net is a dictionary, not normally a tensor. It is not clear for me how to run it with batch size > 1.

Thanks.

**Comment by Skydes** [comment]
Yes, SuperGlue supports batching as long as each image pair contains the same number of keypoints. SuperPoint also supports batching if the images have the same size, but can produce a different number of keypoints for each image. You would thus need to add dummy keypoints between SuperPoint and SuperGlue.

**Comment by oldshuren** [comment]
Thanks Skydes!

What the value of the dummy value of  keypoints and descriptor should be? Is 0 going to work?

Another question.  As I understand if 'keypoints0' is [N keypoints], all keypoints should be the same size.  Does 'keypoints1' need to the same size as 'keypoints0'? 

Thanks again!

**Comment by oldshuren** [comment]
Just tried. Only needs to be them same size within a feature. Feature 0 and feature 1 can have different size.

Thanks!

**Comment by shihaocao** [comment]
I have run with a value of 0, and it works well
