### ISSUE TITLE
How to evaluate and visualize for our own image pair?

### ISSUE THREAD

**Issue by SaugatBhattarai** [magicleap/SuperGluePretrainedNetwork#65]
I wanted to evaluate and visualize my own image pair. Here, I can only check from assets/scannet_sample_images and in its respected  'assets/scannet_sample_pairs_with_gt.txt'  file. I want to generate my own image/text pair. Using these keypoints and descriptions I want to use for medical image registration.

**Comment by Skydes** [comment]
[The README explains the format of the text file.](https://github.com/magicleap/SuperGluePretrainedNetwork#test-set-pair-file-format-explained) The `input_dir` argument can be any directory containing images.

**Comment by SaugatBhattarai** [comment]
Thank you I found in Readme under "Test set pair file format explained"
