### ISSUE TITLE
Can not reproduce results on local feature challenge(aachen v1.1)

### ISSUE THREAD

**Issue by zehongs** [magicleap/SuperGluePretrainedNetwork#66]
Hi @Skydes , great job!
I'm trying to run superglue on the local feature challenge (Aachen v1.1). But I can only get  70.7 for the 0.25m/2° criterion, compared to 73.3. Do you have any suggestion for improving this?

I'm using the code and parameters from the HLoc-toolbox without any modification. For local feature challenge, I'm using the official code. 
```
{'output': 'feats-superpoint-n4096-r1024',
 'model': {'name': 'superpoint', 'nms_radius': 3, 'max_keypoints': 4096},
 'preprocessing': {'grayscale': True, 'resize_max': 1024}}

{'output': 'matches-superglue',
 'model': {'name': 'superglue',
  'weights': 'outdoor',
  'sinkhorn_iterations': 50}}
```

**Comment by Skydes** [comment]
This issue would be better over [cvg/Hierarchical-Localization](https://github.com/cvg/Hierarchical-Localization). For Aachen v1.1, check the dev branch and the new configuration that resizes images to a larger resolution: https://github.com/cvg/Hierarchical-Localization/blob/dev/hloc/extract_features.py#L37-L51

**Comment by zehongs** [comment]
I'm sorry that I missed the `dev` branch in HLoc repository. 
With that config, I got a better result 72.8 / 88.5 / 98.4, which is very close to 73.3 / 88.0 / 98.4. Thank you!
