### ISSUE TITLE
How to create pairs_gt.txt

### ISSUE THREAD

**Issue by shuiliuliushui** [magicleap/SuperGluePretrainedNetwork#69]
Hi,
    Now I want to test SuperGlue on TUM.
    I konw the file format is as following.
path_image_A path_image_B exif_rotationA exif_rotationB [KA_0 ... KA_8] [KB_0 ... KB_8] [T_AB_0 ... T_AB_15]
    But I don't know how to create T_AB correctly by using TUM groundth.txt.
    Could you please do me a favor if you don't mind?

**Comment by ChrisLLLLL** [comment]
Hi, has your problem been solved? I also encountered the same difficulty

**Comment by Skydes** [comment]
The ground truth file in the TUM RGBD dataset is provided as the absolute pose of each frame in world coordinates `T_Aw`. To evaluate SuperGlue, you will need to define image pairs and to compute a relative pose for each pair: 
```T_AB = T_Aw.inv() @ T_Bw```,
where `T_AB` is the transformation from frame A to frame B.

**Comment by ChrisLLLLL** [comment]
Sorry,If I want to evaluate any picture taken randomly, how will I get[KA_0 ... KA_8] [KB_0 ... KB_8] [T_AB_0 ... T_AB_15]? I don't know how to compute.
Looking forward to your reply.

**Comment by Skydes** [comment]
You will need to get a pose in another way, this is not trivial. This is issue is unrelated to this codebase.
Please @shuiliuliushui feel free to close this issue if your problem is solved.

**Comment by shuiliuliushui** [comment]
Thank you
