### ISSUE TITLE
For megadepth training, how to deal with the points without gt depth?

### ISSUE THREAD

**Issue by archershot** [magicleap/SuperGluePretrainedNetwork#72]
When i reproduce train on megadepth, i find that there are somes parts of superpoints without gt depth. 
So i cannot check whether it has the correspondece point in another image.
How should i deal with these points? ignore or treat them as no match?

**Comment by archershot** [comment]
And should these points add to superglue for training?

**Comment by Skydes** [comment]
These point should still be given as input to SuperGlue, but they should be ignored when computing the loss.

**Comment by archershot** [comment]
> These point should still be given as input to SuperGlue, but they should be ignored when computing the loss.

thank you very much!

**Comment by Skydes** [comment]
Please close this issue if your problem is solved.
