### ISSUE TITLE
Extent of homographies for synthetic pre-training

### ISSUE THREAD

**Issue by Valentyn1997** [magicleap/SuperGluePretrainedNetwork#75]
I am trying to reproduce synthetic pre-training via random homographies and photometric transformations. In Figure 13 in the paper, you show some examples, where random homographies are limited to those, which e.g. have only magnifying scaling.
I wonder, what are the **limitations on generating homographies,** such as min percentage of occluded keypoints?

**Comment by Skydes** [comment]
Sorry for the late reply. I am not sure to understand what you mean by "limitations". The homographies that we sample, including those shown in Fig 13, are not limited to scale changes. They have large perspective transformations and some rotation. We sampled them based on hand-tuned boundary values but did not enforce a minimum number of covisible points.

**Comment by Valentyn1997** [comment]
Ok, got it. Thanks!
