### ISSUE TITLE
Keep the input images' size originally

### ISSUE THREAD

**Issue by BruceWANGDi** [magicleap/SuperGluePretrainedNetwork#76]
Hi,
When I run the code 'match_pairs.py', Is there any solution that I can keep my own input images' size originally?
How can I modify the code to keep my own input images' size unchanged?
I really need your support, thank you so much.
I will be looking forward to your reply.

**Comment by Xylon-Sean** [comment]
> ch.
> I will be looking forward to your reply.

You could run `match_pairs.py` follow with `--resize -1` to keep your own input image size unchanged.

**Comment by BruceWANGDi** [comment]
@Xylon-Sean Thx for your timely response.

**Comment by Xylon-Sean** [comment]
@BruceWANGDi no sweating 😊
