### ISSUE TITLE
The usage of 'bin_score' and 'match_threshold'?

### ISSUE THREAD

**Issue by archershot** [magicleap/SuperGluePretrainedNetwork#78]
I found that in the inference phase, output matches is nothing to do with bin_score. And the filter value of 'match_threshold' is a constant value that may affect by sinkhorn iteration and keypoints number. Could the 'bin_score' used as the threshold of unmatch like the training phase?
I test superglue_outdoor weight of yfcc dataset and found that lower 'match_threshold' result in lower precision but higher mscore and localization result. When 'match_threshold' set as 0, the inference match result is nothing to do with sinkhorn. And the localizaiton result still keep robust.

**Comment by Skydes** [comment]
Hi,
The number of Sinkhorn iterations should not matter much as long as it is sufficiently large (we did observe that performing fewer 1-5 iterations sometimes help by increasing the recall, but did not investigate this further). The keypoint number does affect the final score, but that is negligible when the predictions are sensible.

The tradeoff between recall and precision is tricky as it depends on the RANSAC parameters, on the outlier ratio, on the accuracy of the keypoints, so is essentially dataset-dependent. Decreasing the threshold might help in situations with few good matches but not in others.

You could indeed also tune the bin score to adjust the bin penalty, although a good value depends on the magnitude of the scores and is less interpretable.

**Comment by archershot** [comment]
> Hi,
> The number of Sinkhorn iterations should not matter much as long as it is sufficiently large (we did observe that performing fewer 1-5 iterations sometimes help by increasing the recall, but did not investigate this further). The keypoint number does affect the final score, but that is negligible when the predictions are sensible.
> 
> The tradeoff between recall and precision is tricky as it depends on the RANSAC parameters, on the outlier ratio, on the accuracy of the keypoints, so is essentially dataset-dependent. Decreasing the threshold might help in situations with few good matches but not in others.
> 
> You could indeed also tune the bin score to adjust the bin penalty, although its value depends on the magnitude of the scores and is less interpretable.

Thank you for your reply！
