### ISSUE TITLE
Question about training with Oxford and Paris dataset

### ISSUE THREAD

**Issue by rust-in** [magicleap/SuperGluePretrainedNetwork#79]
Hi, 

Thank you for this solid work.

While I am trying to reproduce your work, I notice that the "Revisiting Oxford and Paris dataset(revisitop1m)" is splited into training, validation and test sets. But I can't find the exact ratio or other information on how to split the dataset like paper did.

Could you please share more information about this operation?

Thanks.

**Comment by Skydes** [comment]
Hi,
There is not train/val/test split for the 1M distractors. Note that we did not use the non-distractor images of Oxford & Paris. We randomly selected about 100k images out of 1M, which is largely sufficient to avoid overfitting. Sadly I do not have the list of images, but I think that this does not matter much in practice.

**Comment by rust-in** [comment]
> Hi,
> There is not train/val/test split for the 1M distractors. Note that we did not use the non-distractor images of Oxford & Paris. We randomly selected about 100k images out of 1M, which is largely sufficient to avoid overfitting. Sadly I do not have the list of images, but I think that this does not matter much in practice.

Thank you very much for your reply!
