### ISSUE TITLE
Unable to Reproduce the Number with pretrained model in Scannet pose estimation

### ISSUE THREAD

**Issue by lijiaman** [magicleap/SuperGluePretrainedNetwork#82]
Hi there,

I followed the steps in github to evaluate the pre-trained superglue model in pose estimation evaluation with Scannet test data. But I got the number as follows. 

AUC@5    AUC@10  AUC@20  Prec    MScore
14.69    32.56   50.86   84.35   31.40

Which is worse than the reported number in github. I have tried the same opencv-python version as mentioned in README, it still gave this number. Any clues about this? Appreciate any feedback and help!

**Comment by lijiaman** [comment]
Found the reason, there's difference between scannet data extracted with python and C++ SensReader.  Keeping images and intrinsic consistent solved the issue.

**Comment by vdvchen** [comment]
Hi, could you please provide some additional details? Does that mean some intrinsics extracted from python api are wrong/misaligned?

> Found the reason, there's difference between scannet data extracted with python and C++ SensReader. Keeping images and intrinsic consistent solved the issue.

**Comment by szgy66** [comment]
> Found the reason, there's difference between scannet data extracted with python and C++ SensReader. Keeping images and intrinsic consistent solved the issue.

Hi, I got a worse result. So I want to ask you how to solve it. thanks a lot.
