### ISSUE TITLE
Question about mdesc similarity scores

### ISSUE THREAD

**Issue by Wzj02200059** [magicleap/SuperGluePretrainedNetwork#89]
Thank you for your awesome work!
I found when gnn finish message aggregation，then an Inner product used to get the similarity between mdesc0 and mdesc1.
“scores = torch.einsum('bdn,bdm->bnm', mdesc0, mdesc1)”
i'm noticed the norm of mdesc0 and mdesc1 is different. Could Inner product represent similarity？
Why there has not normalization to mdesc？
Thank you very much if you can answer my questions。

**Comment by baihaozi12** [comment]
I got the same issues, could someone answer me?

**Comment by DaBaiHao** [comment]
It's really a great job, I got the same issue. I can't waiting to see the result of that question

**Comment by Wzj02200059** [comment]
> I got the same issues, could someone answer me?

**Comment by Wzj02200059** [comment]
> I got the same issues, could someone answer me?

I got the answer after read the paper of transformer
