### ISSUE TITLE
Does the descriptor types limit the performance of SuperGlue?

### ISSUE THREAD

**Issue by Xylon-Sean** [magicleap/SuperGluePretrainedNetwork#9]
Since SuperGlue was trained under SuperPoint descriptor, if we place SuperGlue after other descriptors, like R2D2 or D2-Net, will it cause the performance of SuperGlue to degrade?

**Comment by Skydes** [comment]
That's a good question :) Since SuperGlue takes raw descriptors as input, it is tailored to SuperPoint descriptors only. As such, you should retrain it if you want to match other descriptors like R2D2 or D2-Net.

**Comment by Xylon-Sean** [comment]
@Skydes I got it. Thank you very much. 😄
