### ISSUE TITLE
Adding random keypoints during training

### ISSUE THREAD

**Issue by santelelle** [magicleap/SuperGluePretrainedNetwork#90]
Thanks for the really good work! I would have few questions about the random superpoint keypoints added during training to build the batches:
1) Is superpoint run with the default threshold 0.005 during training?
2) The random keypoints are added with score = 0 as stated here #3  #81. A small portion of those random keypoints will qualify as good matches, are those matches used in the loss computation too?
3) For scannet training, superpoint with threshold 0.005 is only able to detect on average ~180 keypoints on images crop 400x400, so I need to add a lot of random keypoints to reach the 400 mentioned on the paper. Did you lower the superpoint detection threshold for this training? Do you remember what crop size did you use for this training?

Thank you!

**Comment by Skydes** [comment]
Hi,
1. I indeed used a threshold of 0.005 for the detection, but dropping it to 0.001 could be safer, especially on ScanNet.
2. Yes, the matches that involve random keypoints are also used in the computation of the loss.
3. For ScanNet we used the full 640x480 resolution without any random crop.
